
	学业进展
	
	“/Jwweb”应用程序中的服务器错误。
编译错误
说明: 在编译向该请求提供服务所需资源的过程中出现错误。请检查下列特定错误详细信息并适当地修改源代码。

编译器错误信息: CS1501: 重载“DrawMainXSXYYZ”方法未获取“1”参数

源错误:


行 20： 
行 21： Response.Output.Write(pSub.HtmlHear());
行 22： Response.Output.Write(xsxj.DrawMainXSXYYZ(USER_ID));
行 23： Response.Output.Write(pSub.HtmlTrail());
行 24： %>


源文件: C:\KINGOSOFT\KINGOJWGL\JWWEB\xsxj\Stu_xyjzqk_rpt.aspx    行: 22


显示详细的编译器输出:

显示完整的编译源:


版本信息: Microsoft .NET Framework 版本:1.1.4322.2512; ASP.NET 版本:1.1.4322.2515 

    
源文件: C:\KINGOSOFT\KINGOJWGL\JWWEB\xsxj\Stu_xyjzqk_rpt.aspx    行: 22 



显示详细的编译器输出:


c:\windows\system32\inetsrv> "c:\windows\microsoft.net\framework\v1.1.4322\csc.exe" /t:library /utf8output /R:"c:\windows\microsoft.net\framework\v1.1.4322\temporary asp.net files\jwweb\efd8f7e4\cc336b3f\r1odsst_.dll" /R:"c:\windows\assembly\gac\system.drawing\1.0.5000.0__b03f5f7f11d50a3a\system.drawing.dll" /R:"c:\windows\microsoft.net\framework\v1.1.4322\temporary asp.net files\jwweb\efd8f7e4\cc336b3f\assembly\dl2\aad2e92b\000cdd1d_86b2cd01\kingo.webreference.uia.dll" /R:"c:\windows\microsoft.net\framework\v1.1.4322\temporary asp.net files\jwweb\efd8f7e4\cc336b3f\assembly\dl2\07351bcf\00d727dd_cfbdd001\kingojw.web.home.dll" /R:"c:\windows\microsoft.net\framework\v1.1.4322\temporary asp.net files\jwweb\efd8f7e4\cc336b3f\assembly\dl2\12df6816\002ff5b7_47eecd01\kingojw.core.dll" /R:"c:\windows\microsoft.net\framework\v1.1.4322\temporary asp.net files\jwweb\efd8f7e4\cc336b3f\assembly\dl2\fb20f099\006b659d_2679cd01\kingonet.secret.dll" /R:"c:\windows\microsoft.net\framework\v1.1.4322\temporary asp.net files\jwweb\efd8f7e4\cc336b3f\assembly\dl2\aef93baa\0047e2c6_ed1cd101\cll.dll" /R:"c:\windows\assembly\gac\system.xml\1.0.5000.0__b77a5c561934e089\system.xml.dll" /R:"c:\windows\assembly\gac\system.enterpriseservices\1.0.5000.0__b03f5f7f11d50a3a\system.enterpriseservices.dll" /R:"c:\windows\microsoft.net\framework\v1.1.4322\temporary asp.net files\jwweb\efd8f7e4\cc336b3f\assembly\dl2\45a3c5ed\20fd05ee_3f68cc01\kingosoft.cl.casagent.dll" /R:"c:\windows\microsoft.net\framework\v1.1.4322\temporary asp.net files\jwweb\efd8f7e4\cc336b3f\assembly\dl2\46e3175e\000cdd1d_86b2cd01\webchart.dll" /R:"c:\windows\microsoft.net\framework\v1.1.4322\temporary asp.net files\jwweb\efd8f7e4\cc336b3f\assembly\dl2\736e93eb\0047e2c6_ed1cd101\dal.dll" /R:"c:\windows\microsoft.net\framework\v1.1.4322\temporary asp.net files\jwweb\efd8f7e4\cc336b3f\assembly\dl2\00e0d60b\006c1777_9726c801\security.dll" /R:"c:\windows\microsoft.net\framework\v1.1.4322\temporary asp.net files\jwweb\efd8f7e4\cc336b3f\assembly\dl2\3cf45507\000cdd1d_86b2cd01\com.idsignet.liberty.idtoken_cs.dll" /R:"c:\windows\assembly\gac\system.data\1.0.5000.0__b77a5c561934e089\system.data.dll" /R:"c:\windows\assembly\gac\system.web.mobile\1.0.5000.0__b03f5f7f11d50a3a\system.web.mobile.dll" /R:"c:\windows\microsoft.net\framework\v1.1.4322\temporary asp.net files\jwweb\efd8f7e4\cc336b3f\assembly\dl2\3e8164fb\00cca2f8_50b9c801\kingo.webreference.thirdparty.shlxuia.dll" /R:"c:\windows\microsoft.net\framework\v1.1.4322\temporary asp.net files\jwweb\efd8f7e4\cc336b3f\assembly\dl2\b7771181\0051c84e_ee1cd101\bll.dll" /R:"c:\windows\assembly\gac\system.web.services\1.0.5000.0__b03f5f7f11d50a3a\system.web.services.dll" /R:"c:\windows\microsoft.net\framework\v1.1.4322\temporary asp.net files\jwweb\efd8f7e4\cc336b3f\assembly\dl2\5d64d15b\000cdd1d_86b2cd01\kingolib.dll" /R:"c:\windows\assembly\gac\system\1.0.5000.0__b77a5c561934e089\system.dll" /R:"c:\windows\assembly\gac\system.web\1.0.5000.0__b03f5f7f11d50a3a\system.web.dll" /R:"c:\windows\microsoft.net\framework\v1.1.4322\temporary asp.net files\jwweb\efd8f7e4\cc336b3f\assembly\dl2\865f344f\00cbb9de_ed1cd101\kingosoftframe.dll" /R:"c:\windows\microsoft.net\framework\v1.1.4322\mscorlib.dll" /out:"C:\WINDOWS\Microsoft.NET\Framework\v1.1.4322\Temporary ASP.NET Files\jwweb\efd8f7e4\cc336b3f\p9rskcyv.dll" /D:DEBUG /debug+ /optimize- /warnaserror /w:1  "C:\WINDOWS\Microsoft.NET\Framework\v1.1.4322\Temporary ASP.NET Files\jwweb\efd8f7e4\cc336b3f\p9rskcyv.0.cs"


Microsoft (R) Visual C# .NET 编译器版本 7.10.6310.4
用于 Microsoft (R) .NET Framework 版本 1.1.4322
版权所有 (C) Microsoft Corporation 2001-2002。保留所有权利。

C:\KINGOSOFT\KINGOJWGL\JWWEB\xsxj\Stu_xyjzqk_rpt.aspx(22,23): error CS1501: 重载“DrawMainXSXYYZ”方法未获取“1”参数
c:\WINDOWS\Microsoft.NET\Framework\v1.1.4322\Temporary ASP.NET Files\jwweb\efd8f7e4\cc336b3f\assembly\dl2\b7771181\0051c84e_ee1cd101\BLL.dll: (与前一个错误相关的符号位置)

 



显示完整的编译源:


行 1：    //------------------------------------------------------------------------------
行 2：    // <autogenerated>
行 3：    //     This code was generated by a tool.
行 4：    //     Runtime Version: 1.1.4322.2512
行 5：    //
行 6：    //     Changes to this file may cause incorrect behavior and will be lost if 
行 7：    //     the code is regenerated.
行 8：    // </autogenerated>
行 9：    //------------------------------------------------------------------------------
行 10：   
行 11：   namespace ASP {
行 12：       using System;
行 13：       using System.Collections;
行 14：       using System.Collections.Specialized;
行 15：       using System.Configuration;
行 16：       using System.Text;
行 17：       using System.Text.RegularExpressions;
行 18：       using System.Web;
行 19：       using System.Web.Caching;
行 20：       using System.Web.SessionState;
行 21：       using System.Web.Security;
行 22：       using System.Web.UI;
行 23：       using System.Web.UI.WebControls;
行 24：       using System.Web.UI.HtmlControls;
行 25：       using ASP;
行 26：       
行 27：       #line 3 "C:\KINGOSOFT\KINGOJWGL\JWWEB\xsxj\Stu_xyjzqk_rpt.aspx"
行 28：       using BLL.XSXJ;
行 29：       
行 30：       #line default
行 31：       #line hidden
行 32：       
行 33：       
行 34：       [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
行 35：       public class Stu_xyjzqk_rpt_aspx : System.Web.UI.Page, System.Web.SessionState.IRequiresSessionState {
行 36：           
行 37：           private static bool __initialized = false;
行 38：           
行 39：           private static System.Collections.ArrayList __fileDependencies;
行 40：           
行 41：           public Stu_xyjzqk_rpt_aspx() {
行 42：               System.Collections.ArrayList dependencies;
行 43：               if ((ASP.Stu_xyjzqk_rpt_aspx.__initialized == false)) {
行 44：                   dependencies = new System.Collections.ArrayList();
行 45：                   dependencies.Add("C:\\KINGOSOFT\\KINGOJWGL\\JWWEB\\xsxj\\Stu_xyjzqk_rpt.aspx");
行 46：                   ASP.Stu_xyjzqk_rpt_aspx.__fileDependencies = dependencies;
行 47：                   ASP.Stu_xyjzqk_rpt_aspx.__initialized = true;
行 48：               }
行 49：               this.Server.ScriptTimeout = 30000000;
行 50：           }
行 51：           
行 52：           protected override bool SupportAutoEvents {
行 53：               get {
行 54：                   return false;
行 55：               }
行 56：           }
行 57：           
行 58：           protected ASP.Global_asax ApplicationInstance {
行 59：               get {
行 60：                   return ((ASP.Global_asax)(this.Context.ApplicationInstance));
行 61：               }
行 62：           }
行 63：           
行 64：           public override string TemplateSourceDirectory {
行 65：               get {
行 66：                   return "/jwweb/xsxj";
行 67：               }
行 68：           }
行 69：           
行 70：           private void __BuildControlTree(System.Web.UI.Control __ctrl) {
行 71：               __ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.__Render__control1));
行 72：           }
行 73：           
行 74：           private void __Render__control1(System.Web.UI.HtmlTextWriter __output, System.Web.UI.Control parameterContainer) {
行 75：               
行 76：               #line 5 "C:\KINGOSOFT\KINGOJWGL\JWWEB\xsxj\Stu_xyjzqk_rpt.aspx"
行 77：               
行 78：   BLL.XSXJ.XSXJ_XSDA pSub=new BLL.XSXJ.XSXJ_XSDA(this);
行 79：   BLL.XSXJ.XSXJ_STU xsxj=new BLL.XSXJ.XSXJ_STU();
行 80：   string USER_ID=pSub.USER_ID;
行 81：   string USER_ZH=pSub.USER_ZH;
行 82：   string USER_NAME=pSub.USER_NAME;
行 83：   string USER_LVID=pSub.USER_LVID;
行 84：   string USER_BJID=pSub.USER_BJID;
行 85：   string USER_LEVEL=pSub.USER_LEVEL;
行 86：   string USER_OPTYX=pSub.USER_OPTYX;
行 87：   string USER_OPTDW=pSub.USER_OPTDW;
行 88：   
行 89：   int R=0;
行 90：   
行 91：   //USER_ID="02011034";
行 92：   
行 93：   Response.Output.Write(pSub.HtmlHear());
行 94：   Response.Output.Write(xsxj.DrawMainXSXYYZ(USER_ID));
行 95：   Response.Output.Write(pSub.HtmlTrail());
行 96：   
行 97：               
行 98：               #line default
行 99：               #line hidden
行 100：              __output.Write("\r\n<FONT face=\"宋体\"></FONT>\r\n");
行 101：          }
行 102：          
行 103：          protected override void FrameworkInitialize() {
行 104：              this.__BuildControlTree(this);
行 105：              this.FileDependencies = ASP.Stu_xyjzqk_rpt_aspx.__fileDependencies;
行 106：              this.EnableViewStateMac = true;
行 107：          }
行 108：          
行 109：          public override int GetTypeHashCode() {
行 110：              return 2141278421;
行 111：          }
行 112：      }
行 113：  }
行 114：  
 




--------------------------------------------------------------------------------
版本信息: Microsoft .NET Framework 版本:1.1.4322.2512; ASP.NET 版本:1.1.4322.2515 
